# Application Name
spring.application.name=CURRENCY-EXCHANGE

# Server Port
server.port=8006

# Config Server Profile
spring.profiles.active=dev

# Admin Server
spring.boot.admin.client.url=http://localhost:1111

# Eureka Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.cloud.client.hostname=localhost

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=naresh@123

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=*

# Zipkin Configuration
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.myCircuitBraker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.myCircuitBraker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.myCircuitBraker.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.myCircuitBraker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.myCircuitBraker.permitted-number-of-calls-in-half-open-state=5

# Logger
logging.level.root=INFO
logging.level.com.currencyApplication=DEBUG

# Log File
logging.file.name=logs/currency-app.log
